builders:
  source_gen_parts_repro:
    import: "package:source_gen_parts_repro/builder.dart"
    builder_factories: ["create"]
    build_extensions: {".dart": [".custom.dart"]}
    build_to: source
    runs_before:
      - :source_gen_parts_repro_2
  source_gen_parts_repro_2:
    import: "package:source_gen_parts_repro/builder.dart"
    builder_factories: ["create2"]
    build_extensions: {".dart": [".custom2.dart"]}
    build_to: source

targets:
  $default:
    builders:
      :source_gen_parts_repro:
        enabled: true
        generate_for:
          - lib/input*
      :source_gen_parts_repro_2:
        enabled: true
        generate_for:
          - lib/input*
