name: source_gen_parts_repro
version: 1.0.0

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  build: ^1.2.0
  analyzer: ^0.39.0
  source_gen: ^0.9.4
  built_value: ^7.0.0

dev_dependencies:
  build_resolvers: ^1.3.3 
  build_runner: ^1.7.4
  built_value_generator: ^7.0.0