import 'package:built_value/built_value.dart';

part 'input.custom.dart'; // generated by us
part 'input.g.dart'; // generated by source_gen & json_serializable

abstract class Foo implements Built<Foo, FooBuilder> {
  Bar get bar;

  Foo._();

  factory Foo(void Function(FooBuilder) updates) = _$Foo;
}
